### PR TITLE
Drop TLSv1 and TLSv1.1 support from intermediate policy

### PR DESCRIPTION
**Pull request by emansom**
TLS 1.0 is known to be vulnerable and has been declared end of life. TLS 1.2 support is wide-enough that it shouldn't cause any breakage.

### CODE REVIEW

**Comment by chernov585** [comment]
Как ты достал, отвали от меня.

Андрей

30 Ноя 2018 г. 14:15 пользователь "Ewout van Mansom" <
notifications@github.com> написал:

TLS 1.0 is known to be vulnerable and has been declared end of life. TLS
1.2 support is wide-enough that it shouldn't cause any breakage.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/h5bp/server-configs-nginx/pull/210
Commit Summary

   - Drop TLSv1 and TLSv1.1 support from intermediate policy

File Changes

   - *M* h5bp/ssl/policy_intermediate.conf
   <https://github.com/h5bp/server-configs-nginx/pull/210/files#diff-0> (2)

Patch Links:

   - https://github.com/h5bp/server-configs-nginx/pull/210.patch
   - https://github.com/h5bp/server-configs-nginx/pull/210.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/h5bp/server-configs-nginx/pull/210>, or mute the thread

**Comment by LeoColomb** [comment]
In the intermediate profile, I think it's better to stick to the Mozilla recommandation, even if a bit outdated. There is the modern profile for "modern" configuration.

**Comment by chernov585** [comment]
Ты, что непонимаеш, отвали, заебал придурок.

Андрей

30 Ноя 2018 г. 14:26 пользователь "Léo Colombaro" <notifications@github.com>
написал:

@chernov585 <https://github.com/chernov585> Please stop spamming our
thread. If you don't want to receive h5bp/server-configs-nginx
notifications, please Unwatch.
See https://help.github.com/articles/watching-and-unwatching-repositories/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/h5bp/server-configs-nginx/pull/210#issuecomment-443175459>,
or mute the thread

**Comment by emansom** [comment]
It would drop support for Internet Explorer <9, Java <7, Android <4.4.2 and Windows XP.

Dropping Java <7 and Android 4.4 support may pose issues, the other contenders shouldn't be targeted from the intermediate preset.

**Comment by LeoColomb** [comment]
> Dropping Java <7 and Android 4.4 support may pose issues

Well, to be honest, I prefer keeping these values for a large compatibility as a goal for the intermediate profile. We can definitely highlight modern profile, but we should keep the intermediate one as a OK-ish compatible fallback.

**Comment by emansom** [comment]
TLS 1 is [not an OK-ish fallback](https://www.globalsign.com/en/blog/disable-tls-10-and-all-ssl-versions/).

**Comment by LeoColomb** [comment]
> TLS 1 is [not an OK-ish fallback](https://www.globalsign.com/en/blog/disable-tls-10-and-all-ssl-versions/).

OK, agreed, then could you just remove TLSv1? Thanks!

**Comment by emansom** [comment]
> > TLS 1 is [not an OK-ish fallback](https://www.globalsign.com/en/blog/disable-tls-10-and-all-ssl-versions/).
> 
> OK, agreed, then could you just remove TLSv1? Thanks!

According to research from SSLLabs [[1]](https://community.qualys.com/thread/16565-is-there-a-reason-for-still-having-tlsv11-enabled) and Mozilla [[2]](https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls/): 99% of clients that support TLS 1.1, also support TLS 1.2 and prefer connecting with TLS 1.2.

[[1]](https://community.qualys.com/thread/16565-is-there-a-reason-for-still-having-tlsv11-enabled): https://community.qualys.com/thread/16565-is-there-a-reason-for-still-having-tlsv11-enabled
[[2]](https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls/): https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls/

**Comment by LeoColomb** [comment]
For instance, Chrome (Chromium) just started to deprecate TLSv1.0/1.1.
Removal is planned for 2020. 
https://www.chromestatus.com/feature/5654791610957824

An alternative to remove these version here would rename policy files:
* policy_deprecated
* policy_current or policy_mainstream
* policy_future

**Comment by LeoColomb** [comment]
I've just rotated policies as I suggested above.
Thanks again, @emansom!

**Pull request closed without merging**
