### PR TITLE
Extend media and font cache TTL to 1 year

### PR DESCRIPTION
**Pull request by jamieburchell**
As discussed [here](https://github.com/h5bp/server-configs-apache/issues/289#issuecomment-961956078)

### CODE REVIEW

**Review by ArunAru135 — APPROVED** [review]

**Review by ArunAru135 — APPROVED** [review]
Content removed for SPAM

**Comment by ArunAru135** [comment]
Hi Friends lets build better lifestye

**Review by fun4cash — COMMENTED** [review]
Content removed for SPAM

**Comment by fun4cash** [comment]
https://github.com/h5bp/server-configs-nginx/pull/291/commits/e98926a22f14497b417fbed82de611f7da3e0eee

**Comment by LeoColomb** [comment]
So much spam these days! Sorry about that @jamieburchell...
I don't forget your pull request, just need to find some time to handle it.

**Review by LeoColomb — APPROVED** [review]

**Pull request merged**
