### PR TITLE
Enables the use of JIT for regular expressions to speed-up their proc…

### PR DESCRIPTION
**Pull request by GreyXor**
PCRE JIT can speed up processing of regular expressions significantly and most GNU/Linux distributions have the `with-pcre-jit` compiler flag.

### CODE REVIEW

**Comment by LeoColomb** [comment]
Thanks for opening this PR, @GreyXor!
In practice it looks really nice, but in practice it seems our little benchmarks with Actions show a decrease in speed and not the opposite.
Do you have already used this option before?

**Comment by GreyXor** [comment]
Hi @LeoColomb! thanks for the quick feedback.
No I didn't make any benchmark at all. I just relied on the documentation which said `speed up processing of regular expressions significantly.`.

I'll see if I can generate some traffic and make a test environment to benchmark this feature but if you actually haven't seen any improvement in performance, maybe we can just cancel this merge request.

**Review by SineathHun — APPROVED** [review]

**Comment by quantumpacket** [comment]
> In theory it looks really nice, but in practice it seems our little benchmarks with Actions show a decrease in speed and not the opposite.

@LeoColomb  can you post these results? Per the docs:

>  The JIT is available in PCRE libraries starting from version 8.20 built with the --enable-jit configuration parameter. When the PCRE library is built with nginx (--with-pcre=), the JIT support is enabled via the --with-pcre-jit configuration parameter. 

Makes me wonder if the proper parameters are being set when building.

**Comment by LeoColomb** [comment]
@quantumpacket As said in the quoted comment, results are public and can be found in Actions tab. 🙂 
[Before](https://github.com/h5bp/server-configs-nginx/runs/3209958914#step:4:108) and [after](https://github.com/h5bp/server-configs-nginx/pull/282/checks#step:4:108).

**Comment by GreyXor** [comment]
Thanks for the test, maybe depending on some configuration the performance can change ? In any case, the nginx documentation talks about better performance. we can close for now

**Comment by LeoColomb** [comment]
Would love to keep this PR open, because it is an interesting suggestion.
Maybe the diff is visible on larger installations, that why we should make more tests.

**Pull request closed without merging**
