### PR TITLE
added the -s flag to the reload command

### PR DESCRIPTION
**Pull request by LC43**
The nginx documentation advises on using the -s signal to reload configuration.

### CODE REVIEW

**Comment by ohartl** [comment]
why are you talking about the -s reload flag and the command is /etc/init.d/nginx -s restart ??

**Comment by LC43** [comment]
oops, @ohartl, forgot to to replace the command.

**Comment by AD7six** [comment]
I'm not too fond of this change.

Many users of this repository are only superficially familiar with nginx I (sort of deliberately) based the docs off of debian/ubuntu usage. 

Ordinarily the only interface a user needs to nginx is the init.d script (or equivalent). `/etc/init.d/nginx restart` just sends a [HUP](http://nginx.org/en/docs/control.html) via whatever means the service was started. For example on ubuntu the init.d script calls:

    start-stop-daemon --stop --signal HUP --quiet --pidfile /run/nginx.pid --name nginx

which is equivalent to calling `nginx -s reload`, just via the same mechanism that started/manages the process.

Adding this proposed change means users may think reloading the config is something they should, in some way, do differently than starting/stopping/other-things nginx.

So for me, I see confusion added here, rather than something clarified - as a user what is the fundamental benefit to you for this change?

**Comment by LC43** [comment]
hi! the script does that on "reload" at least here in debian. Restart is:

    restart)
                log_daemon_msg "Restarting $DESC" "$NAME"

                # Check configuration before stopping nginx
                if ! test_nginx_config; then
                        log_end_msg 1 # Configuration error
                        exit 0
                fi

                do_stop
                case "$?" in
                        0|1)
                                do_start
                                case "$?" in
                                        0) log_end_msg 0 ;;
                                        1) log_end_msg 1 ;; # Old process is still running
                                        *) log_end_msg 1 ;; # Failed to start
                                esac
                                ;;
                        *)
                                # Failed to stop
                                log_end_msg 1
                                ;;
                esac
                ;;


its a stop, then start.

Reload does:

    reload|force-reload)
                log_daemon_msg "Reloading $DESC configuration" "$NAME"

                # Check configuration before reload nginx
                #
                # This is not entirely correct since the on-disk nginx binary
                # may differ from the in-memory one, but that's not common.
                # We prefer to check the configuration and return an error
                # to the administrator.
                if ! test_nginx_config; then
                        log_end_msg 1 # Configuration error
                        exit 0
                fi

                do_reload
                log_end_msg $?
                ;;

which in turn does: 

     do_reload() {
        start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
        return 0
    }


I know there's a couple of situations that you require to restart, but by reloading, its safer ( it tests the config), and there's no downtime ( if the config fails ).

**Comment by LC43** [comment]
also, i'm not saying using `/etc/init.d/nginx reload` or `nginx -s reload`. 

I just continued from the above commands `nginx -t`

**Comment by AD7six** [comment]
You only wanted to correct restart -> reload?

most init.d scripts for nginx don't provide any useful output for a config test (just pass or fail).

**Comment by LC43** [comment]
well... yeah.

**Comment by AD7six** [comment]
As you've noticed I've been blind to that (over familiar, lazy reading) - could you change the pr to contain only that change? I'd rather _not_ tell users to manage daemon processes directly - when the OS provides them a means to do so itself.

**Comment by LC43** [comment]
sure :D 

drop the text and link to documentation too ?

**Comment by AD7six** [comment]
Yeah I think so, it's definitely useful info that users should be familiar with - but not in a getting-started section (keep it simple).

**Comment by LC43** [comment]
hows this #89 ?

**Comment by AD7six** [comment]
I'd rather just replace the word restart with reload =).

There's no need to teach readers to suck eggs IMO.

**Comment by LC43** [comment]
ok, no more :egg:  sucking! 
4d354d425bf7f57a0ffd392b3a1fda0b1431df71

**Comment by AD7six** [comment]
Thanks for persisting - let's go with that =).

**Comment by LC43** [comment]
wohoo! :D thanks for walking me through it! keep up the great work!

**Pull request merged**
