### PR TITLE
Use the conf.d folder for the root context

### PR DESCRIPTION
**Pull request by GreyXor**
I am in the situation where I need to modify the nginx.conf file automatically. I then have to play with `sed` to find the right line and modify it, which is not very clean since I can't predict content of nginx.conf.

With this new layout we can more easily overwrite the parameters without worrying about the content of nginx.conf

- nginx.conf - the main nginx config
- conf.d/*.conf - configs for `root` context
- http.d/*.conf - configs for `http` context

This makes it easier to modify or add parameters in the nginx.conf file.

### CODE REVIEW

**Comment by LeoColomb** [comment]
Thanks for opening this PR, @GreyXor!
This proposal bring a significant structure change, which I'm not sure to follow completely:

> I then have to play with `sed` to find the right line and modify it, which is not very clean since I can't predict content of nginx.conf.

Why not simply add the line to a custom path with your personal changes?
Exactly as you're doing here but outside of the repo.
I mean, I understand the use case where editing `nginx.conf` can be a bit tricky, but commiting a whole folder with files just containing different values from the recommended one from `nginx.conf` seems a bit overkill.

Why not just adding a commented-out example on how to load external custom files?

Furthermore, the move of `conf.d/` to `http.d/` is not relevant here, and break compatibility with previous versions.

**Comment by GreyXor** [comment]
For your upgrade to [4.0.0](https://github.com/h5bp/server-configs-nginx/pull/280) (major change) it is acceptable to have a compatible break.

The move of `conf.d` to `http.d` it's because it's more logical, the name used makes more sense.

Finally, this new method of changing the configuration for the nginx.conf file is cleaner and more easily automated. It is a much better practice to override the configuration with a `foo.d` file than to modify the file directly

**Comment by LeoColomb** [comment]
@GreyXor 

> it's because it's more logical

Is there a documentation or a standard leading to that logic?

> better practice to override the configuration with a `foo.d` directory than to modify the file directly

I agree.
This is why I suggested to add a single line only to the `nginx.conf` to let include custom values.

**Comment by GreyXor** [comment]
> Is there a documentation or a standard leading to that logic?

No i don't have any documentation about it but as i need two folders, one for the nginx `config` and one for the `http` servers. this is the best name i found.

> I agree.

Thanks

**Comment by LeoColomb** [comment]
> best name i found

This is quite opiniated, and this is why I'm asking. I don't thinks it is reasonable to change the whole repository for this.

May I suggest to add this instead in the `nginx.conf`:
```nginx
# Include files in the custom.d folder.
# Custom configuration and value files should be placed in the custom.d
# folder.
# The configurations should be disabled by prefixing files with a dot.
include custom.d/*.conf;
```

And then a line in `.gitignore` to exclude the folder.

**Comment by GreyXor** [comment]
> > best name i found
> 
> This is quite opiniated, and this is why I'm asking. I don't thinks it is reasonable to change the whole repository for this.

Alpine Linux uses the same method for http.d and conf.d
https://gitlab.alpinelinux.org/alpine/aports/-/commit/383ba9c0a200ed1f4b11d7db74207526ad90bbe3
For a 4.0.0 version it didn't seem very serious to me. But I understand ;) it was only a proposal. Thanks for reviewing though :)

**Comment by LeoColomb** [comment]
> Alpine Linux uses the same method for http.d and conf.d
> [gitlab.alpinelinux.org/alpine/aports/-/commit/383ba9c0a200ed1f4b11d7db74207526ad90bbe3](https://gitlab.alpinelinux.org/alpine/aports/-/commit/383ba9c0a200ed1f4b11d7db74207526ad90bbe3)

Oh, this is really really interesting, thanks for the link!
But you see, and this is my concern, it instantly raise inconsistency and user start "complaining": https://gitlab.alpinelinux.org/alpine/aports/-/issues/12836

> For a 4.0.0

4.0.0 was locked a month ago already 🙂

**Comment by emansom** [comment]
Will this be implemented? I second the desire for separating out root `nginx.conf` changes,  in a similar fashion systemd does for their system services. This makes it easier to integrate with distro specific package managers.

**Comment by LeoColomb** [comment]
As you may have noticed @emansom, @GreyXor has closed his pull request so these changes can't be merged.
I'll probably add the change I suggested in [my previous comment](https://github.com/h5bp/server-configs-nginx/pull/283#issuecomment-886899003) soon, but don't hesitate to open a pull request.
The main idea behind is great, we just have to be careful on the how-to.

**Pull request closed without merging**
