### PR TITLE
Update inline.sh - typo in Usage Example

### PR DESCRIPTION
**Pull request by lukeb**
the reference to basics.conf should be basic.conf

### CODE REVIEW

**Comment by arthurvr** [comment]
Thanks!

**Comment by lukeb** [comment]
Why Closed instead of Merged?

**Comment by arthurvr** [comment]
@lukeb It's merged, I just don't really like merge commits :) Check the commit it's closed from, you still have all the credits :)

**Comment by AD7six** [comment]
@arthurvr in future please just click the merge button =).

**Comment by arthurvr** [comment]
@ad7six if you're strongly against it, I'm fine with that. Although in the past we merged a bunch of stuff this way as well :)

**Comment by lukeb** [comment]
I'm with @AD7six . When the pull request is CLOSED, it looks like it was declined by the repo owners.

**Comment by AD7six** [comment]
Don't know about strongly, I'd rather you didn't do it though. Reasons:

 * It is not immediately obvious from [the history](https://github.com/h5bp/server-configs-nginx/commits/master) that a change came from a pull request. If it's multiple commits this can be confusing/problematic.
 * Commit hashes [otherwise](https://github.com/h5bp/server-configs-nginx/commit/72ad300c952312497e003e107a6ba6fd4b0cfec8) [change
](https://github.com/h5bp/server-configs-nginx/commit/e585b29cd74810fd34894c1b9560b63bd81ec0bd) for the same commit
 * Conversations attached to a commit are lost, since the repo history doesn't contain "the" commit in the pull request where comments were made
 * The pull request is [labelled as merged rather than closed](https://github.com/h5bp/server-configs-nginx/pulls?q=is%3Apr+is%3Aclosed) - note the different icon color.
 * It prevents github from saying [hey that commit was in this pull request](https://github.com/h5bp/server-configs-nginx/commit/cd9384f0964388a4c58f647bc40da907e581bd39):

screenshot from 2015-05-12 19 09 13


@arthurvr use the system, don't fight it =). I would recommend you not doing that in any repo.

**Comment by arthurvr** [comment]
This is what we do at most of the h5bp repos so I just did it this way as a habit. I personally think it keeps the commit log clean. This is a pretty common thing so people generally don't really get confused by this. Also, it doesn't break any history as we add the `Close #123` thing. 

Anyways, again, if you're against it I'm happy to not do it. We've merged other things this way in the past and you never complained :)

**Pull request closed without merging**
